/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) LSTM_v21_MHE_cost_y_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

static const casadi_int casadi_s0[39] = {35, 1, 0, 35, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s4[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};

static const casadi_real casadi_c0[2] = {3.1330011785030365e-002, 8.1867419183254242e-002};
static const casadi_real casadi_c1[32] = {-4.8109439015388489e-001, -8.7548941373825073e-002, -4.4737485051155090e-001, 9.2034734785556793e-002, -4.5633724331855774e-001, -5.6610780954360962e-001, 3.7879323959350586e-001, 5.0127464532852173e-001, -8.2274585962295532e-002, 1.0195219516754150e-001, -4.0359571576118469e-001, -3.4450858831405640e-001, -4.5680344104766846e-001, -1.5705892443656921e-001, -3.8456687331199646e-001, 5.9483474493026733e-001, -5.5037727579474449e-003, 3.0953091382980347e-001, 2.7442198991775513e-001, 1.1097805202007294e-001, 9.3669565394520760e-003, 1.9161945581436157e-001, -5.8722972869873047e-001, 3.2058286666870117e-001, 4.8781847953796387e-001, -4.1404223442077637e-001, 3.7178263068199158e-001, 3.3569580316543579e-001, 5.6983149051666260e-001, -2.3255659639835358e-001, 3.5502251982688904e-001, 1.7910581827163696e-001};

/* LSTM_v21_MHE_cost_y_fun:(i0[35],i1[3],i2[],i3[2])->(o0[5]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real w0, w1, w2, *w3=w+5, *w4=w+7, *w5=w+9, *w6=w+41, w7;
  /* #0: @0 = 0.1 */
  w0 = 1.0000000000000001e-001;
  /* #1: @1 = -0.51882 */
  w1 = -5.1882001347507867e-001;
  /* #2: @2 = 1.34803 */
  w2 = 1.3480333254290144e+000;
  /* #3: @3 = [0.03133, 0.0818674] */
  casadi_copy(casadi_c0, 2, w3);
  /* #4: @4 = zeros(2x1) */
  casadi_clear(w4, 2);
  /* #5: @5 = 
  [[-0.481094, -0.447375, -0.456337, 0.378793, -0.0822746, -0.403596, -0.456803, -0.384567, -0.00550377, 0.274422, 0.00936696, -0.58723, 0.487818, 0.371783, 0.569831, 0.355023], 
   [-0.0875489, 0.0920347, -0.566108, 0.501275, 0.101952, -0.344509, -0.157059, 0.594835, 0.309531, 0.110978, 0.191619, 0.320583, -0.414042, 0.335696, -0.232557, 0.179106]] */
  casadi_copy(casadi_c1, 32, w5);
  /* #6: @6 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 16, w6);
  /* #7: @4 = mac(@5,@6,@4) */
  for (i=0, rr=w4; i<1; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w5+j, tt=w6+i*16; k<16; ++k) *rr += ss[k*2]**tt++;
  /* #8: @3 = (@3+@4) */
  for (i=0, rr=w3, cs=w4; i<2; ++i) (*rr++) += (*cs++);
  /* #9: @7 = @3[0] */
  for (rr=(&w7), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #10: @2 = (@2*@7) */
  w2 *= w7;
  /* #11: @1 = (@1+@2) */
  w1 += w2;
  /* #12: @0 = (@0*@1) */
  w0 *= w1;
  /* #13: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #14: @0 = (@0+@1) */
  w0 += w1;
  /* #15: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #16: @0 = 0.1 */
  w0 = 1.0000000000000001e-001;
  /* #17: @1 = -0.51882 */
  w1 = -5.1882001347507867e-001;
  /* #18: @2 = 1.34803 */
  w2 = 1.3480333254290144e+000;
  /* #19: @7 = @3[1] */
  for (rr=(&w7), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #20: @2 = (@2*@7) */
  w2 *= w7;
  /* #21: @1 = (@1+@2) */
  w1 += w2;
  /* #22: @0 = (@0*@1) */
  w0 *= w1;
  /* #23: @1 = input[0][1] */
  w1 = arg[0] ? arg[0][1] : 0;
  /* #24: @0 = (@0+@1) */
  w0 += w1;
  /* #25: output[0][1] = @0 */
  if (res[0]) res[0][1] = w0;
  /* #26: @0 = input[1][0] */
  w0 = arg[1] ? arg[1][0] : 0;
  /* #27: output[0][2] = @0 */
  if (res[0]) res[0][2] = w0;
  /* #28: @0 = input[1][1] */
  w0 = arg[1] ? arg[1][1] : 0;
  /* #29: output[0][3] = @0 */
  if (res[0]) res[0][3] = w0;
  /* #30: @0 = input[1][2] */
  w0 = arg[1] ? arg[1][2] : 0;
  /* #31: output[0][4] = @0 */
  if (res[0]) res[0][4] = w0;
  return 0;
}

CASADI_SYMBOL_EXPORT int LSTM_v21_MHE_cost_y_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int LSTM_v21_MHE_cost_y_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int LSTM_v21_MHE_cost_y_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void LSTM_v21_MHE_cost_y_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int LSTM_v21_MHE_cost_y_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void LSTM_v21_MHE_cost_y_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void LSTM_v21_MHE_cost_y_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void LSTM_v21_MHE_cost_y_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int LSTM_v21_MHE_cost_y_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int LSTM_v21_MHE_cost_y_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real LSTM_v21_MHE_cost_y_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* LSTM_v21_MHE_cost_y_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* LSTM_v21_MHE_cost_y_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* LSTM_v21_MHE_cost_y_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* LSTM_v21_MHE_cost_y_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int LSTM_v21_MHE_cost_y_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 58;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
