/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) LSTM_v21_MHE_constr_h_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[39] = {35, 1, 0, 35, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s4[8] = {4, 1, 0, 4, 0, 1, 2, 3};

/* ode:(v,M_EM_acc,M_EM_brk,M_fric_brk,phi)->(v_dot) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, w4;
  /* #0: @0 = 0.000862069 */
  w0 = 8.6206896551724137e-004;
  /* #1: @1 = 30.5472 */
  w1 = 3.0547167235494886e+001;
  /* #2: @2 = input[1][0] */
  w2 = arg[1] ? arg[1][0] : 0;
  /* #3: @3 = input[2][0] */
  w3 = arg[2] ? arg[2][0] : 0;
  /* #4: @2 = (@2+@3) */
  w2 += w3;
  /* #5: @3 = input[3][0] */
  w3 = arg[3] ? arg[3][0] : 0;
  /* #6: @2 = (@2+@3) */
  w2 += w3;
  /* #7: @1 = (@1*@2) */
  w1 *= w2;
  /* #8: @2 = 0.483025 */
  w2 = 4.8302471499999994e-001;
  /* #9: @3 = input[0][0] */
  w3 = arg[0] ? arg[0][0] : 0;
  /* #10: @2 = (@2*@3) */
  w2 *= w3;
  /* #11: @2 = (@2*@3) */
  w2 *= w3;
  /* #12: @1 = (@1-@2) */
  w1 -= w2;
  /* #13: @2 = 125.176 */
  w2 = 1.2517560000000000e+002;
  /* #14: @3 = input[4][0] */
  w3 = arg[4] ? arg[4][0] : 0;
  /* #15: @4 = cos(@3) */
  w4 = cos( w3 );
  /* #16: @2 = (@2*@4) */
  w2 *= w4;
  /* #17: @1 = (@1-@2) */
  w1 -= w2;
  /* #18: @2 = 11379.6 */
  w2 = 1.1379600000000000e+004;
  /* #19: @3 = sin(@3) */
  w3 = sin( w3 );
  /* #20: @2 = (@2*@3) */
  w2 *= w3;
  /* #21: @1 = (@1-@2) */
  w1 -= w2;
  /* #22: @0 = (@0*@1) */
  w0 *= w1;
  /* #23: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

/* LSTM_v21_MHE_constr_h_fun:(i0[35],i1[3],i2[],i3[2])->(o0[4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1;
  const casadi_real **arg1=arg+4;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11;
  /* #0: @0 = input[1][0] */
  w0 = arg[1] ? arg[1][0] : 0;
  /* #1: @1 = input[1][1] */
  w1 = arg[1] ? arg[1][1] : 0;
  /* #2: @2 = (@0*@1) */
  w2  = (w0*w1);
  /* #3: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  /* #4: @2 = input[1][2] */
  w2 = arg[1] ? arg[1][2] : 0;
  /* #5: @3 = (@0*@2) */
  w3  = (w0*w2);
  /* #6: output[0][1] = @3 */
  if (res[0]) res[0][1] = w3;
  /* #7: @3 = 9.3 */
  w3 = 9.3000000000000007e+000;
  /* #8: @4 = fabs(@1) */
  w4 = fabs( w1 );
  /* #9: @4 = (@4+@0) */
  w4 += w0;
  /* #10: @5 = input[0][2] */
  w5 = arg[0] ? arg[0][2] : 0;
  /* #11: @6 = 0.0166667 */
  w6 = 1.6666666666666666e-002;
  /* #12: @7 = 0.000862069 */
  w7 = 8.6206896551724137e-004;
  /* #13: @8 = 30.5472 */
  w8 = 3.0547167235494886e+001;
  /* #14: @9 = (@0+@1) */
  w9  = (w0+w1);
  /* #15: @9 = (@9+@2) */
  w9 += w2;
  /* #16: @8 = (@8*@9) */
  w8 *= w9;
  /* #17: @9 = 0.483025 */
  w9 = 4.8302471499999994e-001;
  /* #18: @9 = (@9*@5) */
  w9 *= w5;
  /* #19: @9 = (@9*@5) */
  w9 *= w5;
  /* #20: @8 = (@8-@9) */
  w8 -= w9;
  /* #21: @9 = 125.176 */
  w9 = 1.2517560000000000e+002;
  /* #22: @10 = input[3][0] */
  w10 = arg[3] ? arg[3][0] : 0;
  /* #23: @11 = cos(@10) */
  w11 = cos( w10 );
  /* #24: @9 = (@9*@11) */
  w9 *= w11;
  /* #25: @8 = (@8-@9) */
  w8 -= w9;
  /* #26: @9 = 11379.6 */
  w9 = 1.1379600000000000e+004;
  /* #27: @11 = sin(@10) */
  w11 = sin( w10 );
  /* #28: @9 = (@9*@11) */
  w9 *= w11;
  /* #29: @8 = (@8-@9) */
  w8 -= w9;
  /* #30: @7 = (@7*@8) */
  w7 *= w8;
  /* #31: @8 = 0.05 */
  w8 = 5.0000000000000003e-002;
  /* #32: @8 = (@8*@7) */
  w8 *= w7;
  /* #33: @8 = (@5+@8) */
  w8  = (w5+w8);
  /* #34: @9 = ode(@8, @0, @1, @2, @10) */
  arg1[0]=(&w8);
  arg1[1]=(&w0);
  arg1[2]=(&w1);
  arg1[3]=(&w2);
  arg1[4]=(&w10);
  res1[0]=(&w9);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #35: @8 = (2.*@9) */
  w8 = (2.* w9 );
  /* #36: @7 = (@7+@8) */
  w7 += w8;
  /* #37: @8 = 0.05 */
  w8 = 5.0000000000000003e-002;
  /* #38: @8 = (@8*@9) */
  w8 *= w9;
  /* #39: @8 = (@5+@8) */
  w8  = (w5+w8);
  /* #40: @9 = ode(@8, @0, @1, @2, @10) */
  arg1[0]=(&w8);
  arg1[1]=(&w0);
  arg1[2]=(&w1);
  arg1[3]=(&w2);
  arg1[4]=(&w10);
  res1[0]=(&w9);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #41: @8 = (2.*@9) */
  w8 = (2.* w9 );
  /* #42: @7 = (@7+@8) */
  w7 += w8;
  /* #43: @8 = 0.1 */
  w8 = 1.0000000000000001e-001;
  /* #44: @8 = (@8*@9) */
  w8 *= w9;
  /* #45: @8 = (@5+@8) */
  w8  = (w5+w8);
  /* #46: @9 = ode(@8, @0, @1, @2, @10) */
  arg1[0]=(&w8);
  arg1[1]=(&w0);
  arg1[2]=(&w1);
  arg1[3]=(&w2);
  arg1[4]=(&w10);
  res1[0]=(&w9);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #47: @7 = (@7+@9) */
  w7 += w9;
  /* #48: @6 = (@6*@7) */
  w6 *= w7;
  /* #49: @5 = (@5+@6) */
  w5 += w6;
  /* #50: @4 = (@4*@5) */
  w4 *= w5;
  /* #51: @3 = (@3*@4) */
  w3 *= w4;
  /* #52: @4 = 0.304447 */
  w4 = 3.0444721529509555e-001;
  /* #53: @3 = (@3/@4) */
  w3 /= w4;
  /* #54: output[0][2] = @3 */
  if (res[0]) res[0][2] = w3;
  /* #55: @3 = input[3][1] */
  w3 = arg[3] ? arg[3][1] : 0;
  /* #56: @3 = (@3-@5) */
  w3 -= w5;
  /* #57: output[0][3] = @3 */
  if (res[0]) res[0][3] = w3;
  return 0;
}

CASADI_SYMBOL_EXPORT int LSTM_v21_MHE_constr_h_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int LSTM_v21_MHE_constr_h_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int LSTM_v21_MHE_constr_h_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void LSTM_v21_MHE_constr_h_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int LSTM_v21_MHE_constr_h_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void LSTM_v21_MHE_constr_h_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void LSTM_v21_MHE_constr_h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void LSTM_v21_MHE_constr_h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int LSTM_v21_MHE_constr_h_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int LSTM_v21_MHE_constr_h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real LSTM_v21_MHE_constr_h_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* LSTM_v21_MHE_constr_h_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* LSTM_v21_MHE_constr_h_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* LSTM_v21_MHE_constr_h_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* LSTM_v21_MHE_constr_h_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int LSTM_v21_MHE_constr_h_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 17;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
